### ISSUE TITLE
error IsDirectoryError when Preproccess input data

### ISSUE THREAD

**Issue by kobrafarshidi** [tbmoon/basic_vqa#11]
HI @tbmoon ,
I do all step by step but 
when running  (python3 make_vacabs_for_questions_answers.py --input_dir='../COCO-2015') 
I see some error could you help me 

Traceback (most recent call last):
  File "/home/ubuntu/basic_vqa/utils/make_vacabs_for_questions_answers.py", line 79, in <module>
	main(args)
  File "/home/ubuntu/basic_vqa/utils/make_vacabs_for_questions_answers.py", line 68, in main
	make_vocab_questions(input_dir+'/Questions')
  File "/home/ubuntu/basic_vqa/utils/make_vacabs_for_questions_answers.py", line 16, in make_vocab_questions
	with open(input_dir+'/'+dataset) as f:
IsADirectoryError: [Errno 21] Is a directory: '../datasets/Questions/v2_Questions_Val_mscoco'

**Comment by YAO-EE** [comment]
I'm experiencing the same problem, may I ask how you solved it?
