### ISSUE TITLE
NameError: name 'text_processing' is not defined

### ISSUE THREAD

**Issue by BasselAli1** [tbmoon/basic_vqa#8]
When running `!python ../build_vqa_inputs.py --input_dir='../datasets' --output_dir='../datasets'` 
I see 
`Traceback (most recent call last):
  File "../build_vqa_inputs.py", line 96, in <module>
    main(args)
  File "../build_vqa_inputs.py", line 69, in main
    answer_dict = text_processing.VocabDict(vocab_answer_file)
NameError: name 'text_processing' is not defined`

**Comment by Ali-Jakhar** [comment]
try this import text_helper as text_processing in your build_vqa_inputs.py file
this is work for me.
